# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a0Q_7QLNMx_-2iPp-SIQwXCagQrrV9ZM
"""

#!pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler


with open('mental_health_model.pkl','rb') as file:
  model=pickle.load(file)

st.title("Mental Health Prediction App")

st.write("Fill in the details to predict the likelihood of a mental health condition.")


age = st.slider("Age", 18, 65, 25)
gender = st.selectbox("Gender", ["Male", "Female", "Other"])
self_employed = st.selectbox("Are you self-employed?", ["Yes", "No"])
family_history = st.selectbox("Family history of mental illness?", ["Yes", "No"])
work_interfere = st.selectbox("Work interference due to mental health?", ["Never", "Rarely", "Sometimes", "Often"])
no_employees = st.selectbox("Number of employees in the company", ["1-5", "6-25", "26-100", "100-500", "500-1000", "More than 1000"])

input_df = pd.DataFrame({
    'Age': [age],
    'Gender': [gender],
    'self_employed': [self_employed],
    'family_history': [family_history],
    'work_interfere': [work_interfere],
    'no_employees': [no_employees]
})


if st.button("Predict"):

    prediction = model.predict(input_df)
    probability = model.predict_proba(input_df)

    st.subheader("Prediction Result")
    st.write(f"Prediction: **{'Mental Health Issue' if prediction[0] == 1 else 'No Mental Health Issue'}**")
    st.write(f"Probability: {probability[0][1]*100:.2f}%")

